# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "doublets_scrub"
description: "Module metadata for process doublets_scrub"
keywords:
  - "doublets_scrub"
  - "nextflow"
  - "module"
tools:
  - "doublets_scrub":
      description: "Wrapper process for doublets_scrub"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  -
    - input_1:
        type: string
        description: 'path mudata'

output:
  output_1:
    -
      - output_1:
          type: string
          description: 'path ''mudata_doublet.h5mu'', emit: mudata_doublet'

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
