#!/usr/bin/env python

import argparse
from datetime import datetime


def parse_bool(value: str) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def main():
    parser = argparse.ArgumentParser(description="Generate a lightweight pipeline dashboard page.")
    parser.add_argument("--mode", default="standard", choices=["standard", "hashing"])
    parser.add_argument("--default", default="false")
    parser.add_argument("--output", default="dashboard.html")
    args = parser.parse_args()

    default_mode = parse_bool(args.default)
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    html = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Perturbseq Dashboard</title>
  <style>
    body {{ font-family: Helvetica, sans-serif; margin: 2rem; color: #1f2937; }}
    .meta {{ background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; }}
    h1 {{ margin-bottom: 0.5rem; }}
    code {{ background: #e5e7eb; padding: 0.1rem 0.3rem; border-radius: 0.25rem; }}
  </style>
</head>
<body>
  <h1>Perturbseq Dashboard (Refactor In Progress)</h1>
  <p>This page is generated by a shared dashboard process used by both hashing and non-hashing branches.</p>
  <div class=\"meta\">
    <p><strong>Mode:</strong> {args.mode}</p>
    <p><strong>Default Inference Variant:</strong> {default_mode}</p>
    <p><strong>Generated:</strong> {generated_at}</p>
  </div>
  <p>Next step is to plug the full plotting and table renderers into this unified entrypoint.</p>
</body>
</html>
"""

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(html)


if __name__ == "__main__":
    main()