# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "anndataconcat"
description: "Module metadata for process ANNDATACONCAT"
keywords:
  - "anndataconcat"
  - "nextflow"
  - "module"
tools:
  - "anndataconcat":
      description: "Wrapper process for ANNDATACONCAT"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  output_1:
    -
      - output_1:
          type: string
          description: 'path "concatenated_adata.h5ad", emit: concat_anndata'
  output_2:
    -
      - output_2:
          type: string
          description: 'path "versions.yml",           emit: versions'

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
